runtime: python311
entrypoint: gunicorn cocoon.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
service: cocoon-api

env_variables:
  FILESTORE_BUCKET: cocoonwebsiteprod.appspot.com
  GOOGLE_PROJECT_ID: cocoonwebsiteprod
  GOOGLE_CLIENT_ID: 464711449307-7j2oecn3mkfs1eh3o7b5gh8np3ebhrdp.apps.googleusercontent.com


handlers:
  - url: /.*
    script: auto
    secure: always
