runtime: python311
entrypoint: gunicorn cocoon.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT

env_variables:
  FILESTORE_BUCKET: cocoon-kosk.appspot.com
  GOOGLE_PROJECT_ID: cocoon-kosk
  GOOGLE_CLIENT_ID: 899786740417-dhtk8pilvkhkne3ht3c6ecbnm0619ijm.apps.googleusercontent.com


handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
    secure: always

  - url: /
    static_files: dist/index.html
    secure: always
    upload: dist/index.html

  - url: /([^\.]*)$
    static_files: dist/\1/index.html
    upload: dist/([^\.]*)/index.html
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
