runtime: python311
entrypoint: gunicorn cocoon.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
service: cocoon-api

env_variables:
  FILESTORE_BUCKET: cocoon-kosk.appspot.com
  GOOGLE_PROJECT_ID: cocoon-kosk
  GOOGLE_CLIENT_ID: 899786740417-dhtk8pilvkhkne3ht3c6ecbnm0619ijm.apps.googleusercontent.com
  REDDEVIL_LOGLEVEL=DEBUG


handlers:
  - url: /.*
    script: auto
    secure: always
