[tool.poetry]
name = "cocoon"
version = "2.14.1"
description = "cocoon backend"
authors = ["Ruben Decrop <ruben.decrop@cocoon.be>"]

[tool.poetry.dependencies]
python = "^3.11"
toml = "^0.10.2"
gunicorn = "^21.2.0"
python-dotenv = "^1.0.1"
openpyxl = "^3.1.2"
asyncssh = "^2.14.2"
reddevil = {path = "libs/reddevil-3.3.7-py3-none-any.whl"}

[tool.poetry.group.dev.dependencies]
black = "^23"
pytest = "^7"
pytest-asyncio = "^0.23.5"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
